-- USERS TABLE UPDATE
ALTER TABLE users ADD COLUMN rating INTEGER DEFAULT 800;
ALTER TABLE users ADD COLUMN maxRating INTEGER DEFAULT 800;
ALTER TABLE users ADD COLUMN rankTitle TEXT DEFAULT 'Newbie';
ALTER TABLE users ADD COLUMN rankColor TEXT DEFAULT 'gray';

-- PROBLEMS TABLE UPDATE
ALTER TABLE problems ADD COLUMN difficulty INTEGER DEFAULT 800;

-- SUBMISSIONS UPDATE (nếu chưa có)
ALTER TABLE submissions ADD COLUMN createdAt TEXT;
ALTER TABLE submissions ADD COLUMN problemId INTEGER;